name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Build
        uses: actions/setup-node@v1
       
      - run: | 
          npm install
          npm run build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ppl-be # the name of the project on Deno Deploy
          entrypoint: ./dist/index.js # the entrypoint to deploy