name: Heroku Deploy

on:
  push:
    branches:
    - workflow-testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main 
      - name: deploy
        run: |
          sudo apt-get update
          sudo apt-get install ruby-dev
          sudo gem install dpl
          sudo dpl --provider=heroku --app=ppl-be --api_key=${{secrets.HEROKU_API_KEY}}